[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "embedding"
version = "0.0.1"
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "pandas",
    "scikit-learn",
    "torch",
]
